### ISSUE TITLE
Telegrambot-lib over otan/morse

### ISSUE THREAD

**Issue by Bost** [wdhowe/telegrambot-lib#59]
The source code of your library is tidied and extensively documented. 👍 ❤️

Can you tell me please, is there any other reason besides those two and the one from your README.md [*], why should one prefer your library over the [otan/morse](https://github.com/otann/morse) and FWIW my fork [Bost/morse](https://github.com/Bost/morse)? Otan/morse seems to be stalled, but it has 42+ other forks with a few fixes and minor additions. In my fork I merged them together. 

Also, can you tell me please who else is using your library and do you have e.g. a telegram-channel where people can contact you?

To be more specific, I use morse in this project of mine [Bost/corona_cases](https://github.com/Bost/corona_cases), which, oddly enough, while still rather small, seems to be the biggest Clojure Telegram Bot to be found on Github and/or Gitlab. IOW the "Clojure Telegram Bots" community is a rather lonely place to be. But then I found you...

Thanks

[*] "[telegrambot-lib aims to be a] complete implementation of the Telegram Bot API in Clojure, without adding extra bot logic"

**Comment by wdhowe** [comment]
Hi there, thank you for the interest in this project!

I started this project because I was looking to learn/create a Telegram bot for fun and wanted a simple/complete library to access the Telegram bot API from Clojure.

I looked through all available projects on Clojars and didn't quite find what I was looking for.

Morse does look great for common functionality and some extra handling of patterns.

I am not sure who else is using my library. I currently do not have a channel where people can contact me.

I have attempted to contact Telegram's bot support with a suggestion to get this library added to the bot samples page (https://core.telegram.org/bots/samples), but I have not heard back.
